version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8040
    volumes:
      - .:/app
    ports:
      - "8040:8040"
    environment:
      - DJANGO_SETTINGS_MODULE=Portfolio.settings