# Generated by Django 5.1 on 2024-08-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndustryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='technologies',
        ),
    ]
