# Generated by Django 5.1 on 2024-08-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndustryApp', '0002_remove_customer_technologies'),
        ('ProjectApp', '0004_projectdetail_technologies_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
