# Generated by Django 5.1 on 2024-08-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndustryApp', '0003_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='main_technology',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='technology_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
