# Generated by Django 5.1 on 2024-08-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndustryApp', '0004_technology_main_technology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_description', models.TextField(blank=True, null=True)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='customer_images/')),
                ('technologies', models.ManyToManyField(related_name='customer', to='IndustryApp.technology')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
