# Generated by Django 5.1 on 2024-08-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndustryApp', '0005_customer'),
        ('ProjectApp', '0008_company_alter_projectdetail_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
