# Generated by Django 5.1 on 2024-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndustryApp', '0006_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255)),
                ('element_description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Customer Element',
                'verbose_name_plural': 'Customer Elements',
            },
        ),
    ]
