# Generated by Django 5.1 on 2024-08-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndustryApp', '0007_customerelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='IndustryApp.customer')),
                ('elements', models.ManyToManyField(related_name='customer_details', to='IndustryApp.customerelement')),
            ],
            options={
                'verbose_name': 'Customer Detail',
                'verbose_name_plural': 'Customer Details',
            },
        ),
    ]
