# Generated by Django 5.1 on 2024-08-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('years', models.PositiveIntegerField(blank=True, null=True)),
                ('job_role', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('what_i_learned', models.TextField(blank=True, null=True)),
                ('life_circumstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.lifecircumstance')),
            ],
            options={
                'verbose_name': 'Biography',
                'verbose_name_plural': 'Biographies',
            },
        ),
    ]
