# Generated by Django 5.1 on 2024-08-22 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndustryApp', '0002_remove_customer_technologies'),
        ('ProjectApp', '0003_rename_projectresult_projectoutcome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='technologies',
            field=models.ManyToManyField(related_name='project_details', to='IndustryApp.technology'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_description', models.TextField(blank=True, null=True)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='customer_images/')),
                ('technologies', models.ManyToManyField(related_name='customer', to='IndustryApp.technology')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to='ProjectApp.customer'),
        ),
    ]
