# Generated by Django 5.1 on 2024-08-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0004_projectdetail_technologies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('category_icon', models.ImageField(blank=True, null=True, upload_to='category_files/')),
            ],
        ),
        migrations.AlterField(
            model_name='cv',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='ProjectApp.category'),
        ),
    ]
