# Generated by Django 5.1 on 2024-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0005_category_alter_cv_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
