# Generated by Django 5.1 on 2024-08-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndustryApp', '0005_customer'),
        ('ProjectApp', '0006_alter_category_options_reference_reference_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to='IndustryApp.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
