# Generated by Django 5.1 on 2024-08-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0008_company_alter_projectdetail_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_detail',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_icon',
        ),
    ]
