# Generated by Django 5.1 on 2024-08-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0009_remove_project_project_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
