# Generated by Django 5.1 on 2024-08-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0012_element_customer_element_project_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectoutcome',
            name='project_id',
        ),
    ]
