# Generated by Django 5.1 on 2024-08-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0014_projectdetail_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
