# Generated by Django 5.1 on 2024-08-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0015_delete_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
