# Generated by Django 5.1 on 2024-08-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0016_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
